# Generated by Django 3.0.8 on 2020-07-30 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userfilepath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(null=True)),
                ('filepath', models.CharField(max_length=50, null=True)),
                ('date', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
